---
title: "Final Project"
author: "Rohit Kumar & Channing Vernon"
date: "11/12/2019"
output:
  pdf_document: default
  html_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("knitr")
opts_knit$set(root.dir = "C:/Users/William Roche/Documents/GitHub/Git2/S-P500Trends/sandp500")
#Need to make this a relative path so anyone can load the dataset easily

library(tidyverse)
library(dplyr)
#Loading all necessary libraries

```

<br>

# Loading Data + Cleaning
```{r}
## Goals:
# Cleaning up data, making it easier to read. 
# **ALso need to filter out any NA's.**

data <- read.csv("all_stocks_5yr.csv")

summary(data)
str(data)

SP_data <- data %>%
  select(Name,date,open,low,high,close, volume)
# Changing the order of the columns

```


**Ommiting `NA` rows vs replacing them with `0`**
```{r}
SP_data <- na.omit(SP_data)
#SP_data[is.na(SP_data)] <- 0

# Omitting rows with NA values in order to make calculations error free, vs setting them to 0.

summary(SP_data)
```

<br>
# Changing date column from a factro to date
```{r}
# Making the "date" column usable.

SP_data$Date <- as.Date(SP_data$date, format = "%Y-%m-%d")
SP_data$date <- NULL
# Changing the date column format into a new variable, and deleting the previous one

summary(SP_data)

```

```{r, message = FALSE}
## Goals
# Figuring out how to categorize the data into 500 indiviual companies, manually or via
# automation/funtion.

SP_data %>%
  group_by(Name) %>%
  select(Name) %>%
  unique()
# Listing all of the unique companies included in data set.

ABC <- ggplot(filter(SP_data, Name %in% c("ABC")), aes(x = Date, y = close)) + geom_point(alpha = (1/3), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "AmerisourceBergen Corp.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

ABC

AAL <- ggplot(filter(SP_data, Name %in% c("AAL")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "American Airlines",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AAL

AAL_ABC <- ggplot(filter(SP_data, Name %in% c("AAL","ABC")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "American Airlines & AmerisourceBergen Corp.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AAL_ABC






#summary(SP_data)
```


#Top S&P 500 Stocks 
* Categorized by competitors and similar industries
```{r, message = FALSE}

AMD <- ggplot(filter(SP_data, Name %in% c("AMD")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Advanced Micro Devices",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AMD


NVDA <- ggplot(filter(SP_data, Name %in% c("NVDA")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "InVidia",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

NVDA


INTC <- ggplot(filter(SP_data, Name %in% c("INTC")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Intel",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

INTC
```


```{r}

WMT <- ggplot(filter(SP_data, Name %in% c("WMT")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Walmart",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

WMT


AMZN <- ggplot(filter(SP_data, Name %in% c("AMZN")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Amazon",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AMZN


MSFT <- ggplot(filter(SP_data, Name %in% c("MSFT")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Microsoft",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

MSFT


AAPL <- ggplot(filter(SP_data, Name %in% c("AAPL")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Apple",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AAPL

```

```{r}
TRIP <- ggplot(filter(SP_data, Name %in% c("TRIP")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Trip Advisor",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

TRIP


AAP <- ggplot(filter(SP_data, Name %in% c("AAP")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Advance Auto Parts",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AAP



IBM <- ggplot(filter(SP_data, Name %in% c("IBM")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "IBM",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

IBM



RHT <- ggplot(filter(SP_data, Name %in% c("RHT")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Red Hat ",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

RHT

```


```{r}

MCD <- ggplot(filter(SP_data, Name %in% c("MCD")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Mcdonald's Corp.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

MCD


CMG <- ggplot(filter(SP_data, Name %in% c("CMG")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Chipotle Mexican Grill",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

CMG


SBUX <- ggplot(filter(SP_data, Name %in% c("SBUX")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Starbucks",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

SBUX

WEN <- ggplot(filter(SP_data, Name %in% c("WEN")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Wendy's Co",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

WEN

KEYS <- ggplot(filter(SP_data, Name %in% c("KEYS")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Keysight Technologies Inc",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

KEYS


ORLY<- ggplot(filter(SP_data, Name %in% c("ORLY")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "O'Reilly Automotive",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

ORLY


FOX <- ggplot(filter(SP_data, Name %in% c("FOX")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Twentieth Century Fox",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

FOX


DIS <- ggplot(filter(SP_data, Name %in% c("DIS")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Disney",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

DIS

HULU <- ggplot(filter(SP_data, Name %in% c("HULU")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "HULU",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

HULU


HCA <- ggplot(filter(SP_data, Name %in% c("HCA")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "HCA Healthcare",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

HCA


BSX <- ggplot(filter(SP_data, Name %in% c("BSX")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Boston Scientific",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

BSX


MKC <- ggplot(filter(SP_data, Name %in% c("MKC")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "McCormick & Co.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

MKC


ILMN <- ggplot(filter(SP_data, Name %in% c("ILMN")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Ilumina Inc.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

ILMN


NRG <- ggplot(filter(SP_data, Name %in% c("NRG")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "NRG Energy Co.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

NRG


LLY <- ggplot(filter(SP_data, Name %in% c("LLY")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Eli Lilly & Co.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

LLY


NFLX <- ggplot(filter(SP_data, Name %in% c("NFLX")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Netflix",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

NFLX


EW <- ggplot(filter(SP_data, Name %in% c("EW")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Edwards Lifesciences",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

EW


CRM <- ggplot(filter(SP_data, Name %in% c("CRM")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Salesforce.com",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

CRM


AES <- ggplot(filter(SP_data, Name %in% c("AES")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "AES Corporation",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

AES


RMD <- ggplot(filter(SP_data, Name %in% c("RMD")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "ResMed Inc.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

RMD


CHD <- ggplot(filter(SP_data, Name %in% c("CHD")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Church & Dwight Co.",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

CHD


LW <- ggplot(filter(SP_data, Name %in% c("LW")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = " Lamb Weston Holdings",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

LW


VRNS <- ggplot(filter(SP_data, Name %in% c("VRNS")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Verisign",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

VRNS


BRK.A <- ggplot(filter(SP_data, Name %in% c("BRK.A")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Berkshire Hathaway Inc.(A)",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

BRK.A


BRK.B <- ggplot(filter(SP_data, Name %in% c("BRK.B")), aes(x = Date, y = close)) + geom_point(alpha = (1/6), size = 2) + geom_smooth(lwd = 1, se = TRUE) + labs(title = "Berkshire Hathaway Inc.(B)",
                        subtitle = "2013 to 2018",
                        y = "Date",
                        x = "Closing price (USD)")

BRK.B


```



























